spring.application.name=watchcow-consumer
server.port=8282
debug=true


# Database Conifguration ( TimescaleDB )
spring.datasource.url=jdbc:postgresql://localhost:5433/metricsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

